site_name: Intro to Python

# Repository 
repo_name: intro-to-python
repo_url: https://github.com/prof-rossetti/intro-to-python


# link to colors https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  features: 
    # - navigation.tabs # this option gives us tabs at the top
    # - navigation.sections # this active removes the drop down subfolders 
    - navigation.top # look this up 
    - search.sugguest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotation
  palette:
    - scheme: slate
      primary: deep purple 
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  # Right sidebar with the table of contents (requires 'navigation.sections')
  right_sidebar:
    - toc

# Extensions
markdown_extensions:
  # - admonitiondocs
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details


nav:
  - Home: index.md
  - Notes:
    - maingun API: notes/apis/mailgun.md
    - CLIs:
      - brew: notes/clis/brew.md
      - Chromedriver: notes/clis/chromedriver.md
      - Conda: notes/clis/conda.md
      # Assuming there are markdown files for these entries, otherwise remove or add the paths
      - GIT: notes/clis/git.md
      - Heroku: notes/clis/heroku.md
      - PDFtoText: notes/clis/pdftotext.md
      - Pip: notes/clis/pip.md
      - Python: notes/clis/python.md
      - youtube-dl: notes/clis/youtube-dl.md
    # Assuming there are sections and markdown files for these, otherwise you need to add them
    - Devtools:
      - github actions: notes/devtools/github-actions/README.md
      - code climate: notes/devtools/code-climate.md
      - git bash: notes/devtools/git-bash.md
      - git desktop: notes/devtools/git-desktop.md
      - google APIs: notes/devtools/google-apis.md
      - Google colab: notes/devtools/google-colab.md
      - jupyter notebooks: notes/devtools/jupyter-notebooks.md
      - pycharm: notes/devtools/pycharm.md
      - travis-ci: notes/devtools/travis-ci.md
      - VS code: notes/devtools/vs-code.md
    - environment variables:
      # Assuming a markdown file for accessing globally
      - accessing globally: notes/environment-variables/accessing-globally.md
    # Assuming markdown files for these sections or they should be removed or completed
    - hardware: notes/hardware/hardware.md
    - Info systems: notes/info-systems/README.md
      - Data stores: notes/info-systems/datastores.md
      - Networks: notes/info-systems/networks.md
      - People: notes/info-systems/people.md
      - Processes: notes/info-systems/processes.md
      - Security-privacy: notes/info-systems/security-privacy.md
    - python Management: notes/python-mgmt/README.md
      - Dev lifecycle: notes/python-mgmt/dev-lifecycle.md
      - tools: notes/python-mgmt/tools.md
    - Python: notes/python/datatypes/README.md
      - booleans: notes/python/datatypes/booleans.md
      - class interhitence: notes/python/datatypes/class-inheritence.md
      - classes: notes/python/datatypes/classes.md
      - dates: notes/python/datatypes/dates.md
      - dictionaries: notes/python/datatypes/dictionaries.md
      - lists: notes/python/datatypes/lists.md
      - none: notes/python/datatypes/none.md 
      - numbers: notes/python/datatypes/numbers.md










